### ISSUE TITLE
Do you have any interest in using Cocoapods for this project?

### ISSUE THREAD

**Issue by mkral** [StreamCenter/StreamCenter#1]
I think Cocoapods is pretty universal and it allows better dependency management than using submodules. 

Ideally the Pods/ directory would be `.git-ignore` 'd so it's only the Podfile and Podfile.lock being tracked in git. 

Alamofire has a tvOS branch too, in case you didn't know.

**Comment by olivierboucher** [comment]
Yes, I am using the tvOS branch, unless it just wouldn't compile. I sure have an interest in using Cocoapods. I initially wanted to use as few third party libraries as possible but Alamofire does the job so well. Let's go this way in case we add any other dependencies down the road

**Comment by mkral** [comment]
I think you should create at least develop branch that we merge pull requests into also.

**Comment by olivierboucher** [comment]
Doing it right now !

**Comment by mkral** [comment]
I need to migrate to Alamofire 3.0. Almost done.

**Comment by olivierboucher** [comment]
I am having issues with cocoapods right now. 

`[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /Users/olivier/Workspace/Rivus/RivusPrototypes/TestTVApp/Podfile.lock`

Looking for a solution online

**Comment by mkral** [comment]
@OlivierBoucher did you do `pod setup` in the terminal after installing?

**Comment by mkral** [comment]
@OlivierBoucher I'll add that to the read-me if that's the issue

**Comment by olivierboucher** [comment]
@mkral I updated all gems by mistake earlier on. I seemed to have broke the yaml parser. I had to delete the Psych gem that was causing conflict.

**Comment by mkral** [comment]
@OlivierBoucher  so is it working for you now?

**Comment by olivierboucher** [comment]
It is ! I had some warnings but I think you fixed that, I'm a few commits behind

`The `GamingStreamsTVApp [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-GamingStreamsTVApp/Pods-GamingStreamsTVApp.debug.xcconfig'. This can lead to problems with the CocoaPods installation`

Fixed with 4a8c882758fc6ccdbfea3f685ba902d9be9590ff

**Comment by mkral** [comment]
Yea cocoa pods sets all the build settings up required by the dependency so when in doubt either delete the overwritten value or set it to $(inherited)
