### ISSUE TITLE
Add License for Repo

### ISSUE THREAD

**Issue by mkral** [StreamCenter/StreamCenter#10]
You probably should add a License to this repo so people know how they can use it (and before more people start contributing) I'm fine with it being MIT if you are.

**Comment by olivierboucher** [comment]
Agreed. We should also remove all references to my current organization that my xcode added.

**Comment by mkral** [comment]
That's up to you. Do you own Rivus Media? or is that your employer?

**Comment by olivierboucher** [comment]
I am consulting for these guys. I removed all copyrights and added license as of 5cb11cdde3c6590dad1c3449d59c3ca8c2155a32
