### ISSUE TITLE
Errors in TwitchApi.swift

### ISSUE THREAD

**Issue by ghost** [StreamCenter/StreamCenter#13]
Here couple of errors see screenshots
![screen shot 2015-10-07 at 11 29 24 pm](https://cloud.githubusercontent.com/assets/9125110/10358011/860e06ea-6d4e-11e5-8a96-c4370cdee9bb.png)
![screen shot 2015-10-07 at 11 29 31 pm](https://cloud.githubusercontent.com/assets/9125110/10358013/89d1e922-6d4e-11e5-8a78-5af9b6b83de8.png)
![screen shot 2015-10-07 at 11 29 38 pm](https://cloud.githubusercontent.com/assets/9125110/10358015/8c15c438-6d4e-11e5-8abb-d249a73761da.png)

How to fix it?

**Comment by ghost** [comment]
Using Xcode 7.1 beta 3

**Comment by BasThomas** [comment]
You'll need to run `pod install`.

**Comment by ghost** [comment]
Its after pod install, I open GamingStreamsTVApp.xcworkspace and when building this error

**Comment by mkral** [comment]
@StanZabroda  I updated the Alamofire dependency to the tvOS version which is 3.0 so you'll need to work off the develop branch. That's migrated to the Alamofire 3.0

**Comment by mkral** [comment]
We should probably merge that into master so it's build-able.

**Comment by ghost** [comment]
Do anyone have Apple TV Dev Kit? Really need UDID to make provision profile.

**Comment by mkral** [comment]
I should be getting mine tomorrow. (today)

**Comment by ghost** [comment]
Don't know how to fix errors :(

**Comment by mkral** [comment]
Did you try the develop branch?

**Comment by mkral** [comment]
This has been fixed in the develop branch.

**Comment by ghost** [comment]
Did you get Apple TV Dev Kit? Can you share UDID, please?

**Comment by mkral** [comment]
not yet, should be delivered today. Why do you need the UDID though?

**Comment by ghost** [comment]
When trying to make provision it says that you have no registered TVs on you account. I need to register at least 1 Apple TV UDID.

**Comment by mkral** [comment]
Are you just trying to run it in the simulator? You shouldn't need a provisioning profile for that, at the very most a wildcard one.

**Comment by ghost** [comment]
Im trying to make archive of my own project. And it require provision
