### ISSUE TITLE
Validate that we don't break the TOS of Twitch

### ISSUE THREAD

**Issue by olivierboucher** [StreamCenter/StreamCenter#14]
I've had some comments on the reddit thread about this. We need to check what twitch tolerates.

**Comment by mkral** [comment]
Don't have time to review it now but here's the link:

http://www.twitch.tv/user/legal?page=api_terms_of_service

**Comment by mkral** [comment]
### Section 13. Prohibitions.

> ...
> 
> access any portion of any Twitch audiovisual content by any means other than use of the Twitch Player;
> 
> ...

**Comment by mkral** [comment]
Unfortunately it looks like they only allow you using their embedded player (as an iFrame) which sucks since tvOS doesn't allow web views. We might need to re-think how this is implemented, or it might not be possible.

**Comment by mkral** [comment]
I added this question to the twitch github: https://github.com/justintv/Twitch-API/issues/446

**Comment by olivierboucher** [comment]
Well. That throws us off. I'll check if it would be possible to tweak something with webkit. I think that the webview component is not available for tvOS

**Comment by mkral** [comment]
I posted in the Twitch-API repo to ask if they are working on a tvOS solution or if they give written exceptions for tvOS apps. It does suck though.

**Comment by mkral** [comment]
I see lots of apps that use the same methods but I think the issue is you're getting the developers specific m3u8 and in doing so by-passing advertisement.

**Comment by mkral** [comment]
They need to open-source their player in the iOS app (assuming it's native and not web view)

**Comment by olivierboucher** [comment]
They have an app for iOS ! I wonder how much of a problem it is for them to port it and screw us

**Comment by mkral** [comment]
I don't doubt they will release an app for AppleTV but I also feel like they would encourage developers to make 3rd party apps

**Comment by olivierboucher** [comment]
I think the player can use the m3u8 file without any parsing

**Comment by mkral** [comment]
I don't think it screws us either

**Comment by mkral** [comment]
How are you getting the m3u8 playlist though? It's not apart of Twitch's API AFAIK. You're using the usher.twitch.tv endpoint and I'm not sure that's allowed in their ToS either.

**Comment by olivierboucher** [comment]
Yeah, I followed the http requests.. I found a python app that does the same. I'll check for the reference sec

**Comment by olivierboucher** [comment]
https://github.com/chrippa/livestreamer it's not really the same thing but I don't see them being sued by twitch and youtube.

**Comment by mkral** [comment]
I don't think they'll sue, but they will likely change the API's and infrastructure. Check out this reddit thread that the developer replied to from the first time they changed:

https://www.reddit.com/r/Twitch/comments/2p0zka/tardsplaya_stopped_working_for_everyone/cmscmpv

**Comment by olivierboucher** [comment]
I think that the best would be to comply and find a way to use their player. I'll investigate tonight

**Comment by mkral** [comment]
Agreed

**Comment by olivierboucher** [comment]
Should we create a slack channel to exchange?

**Comment by mkral** [comment]
yea probably

**Comment by waterskier2007** [comment]
I'm cool with that.

**Comment by olivierboucher** [comment]
@waterskier2007 I'll need your email !

**Comment by waterskier2007** [comment]
brendankirchner@me.com
