### ISSUE TITLE
Play/Pause support

### ISSUE THREAD

**Issue by waterskier2007** [StreamCenter/StreamCenter#19]

**Comment by waterskier2007** [comment]
feel free to assign this to me, i've already got it working somewhat

**Comment by mkral** [comment]
@OlivierBoucher will have to add you as a collaborator for you to be assigned.

**Comment by waterskier2007** [comment]
no problem

**Comment by olivierboucher** [comment]
@waterskier2007 I just added you as a collaborator ! Thanks alot

**Comment by waterskier2007** [comment]
Do we want this to resume back to the point of the live stream, or just resume after the pause?

**Comment by olivierboucher** [comment]
At the point of the livestream, just like on the web. Is that ok with you?
