### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by olivierboucher** [StreamCenter/StreamCenter#21]
@waterskier2007 already started working on this

**Comment by olivierboucher** [comment]
The way I would see it is that the search would lead to a different view controller, holding both streams and games corresponding to the request. So we would have to make 2 api queries to /search/games and /search/streams. What's your opinion on this?

**Comment by waterskier2007** [comment]
I get that. The UISearchController implementation in tvOS is not as smooth as iOS and all of the documentation that apple provides is literally copy/pasted from iOS even though it's not the same implementation. I do think your idea would be easier to do, so i will take a look. We may just have to use a straight up text field and have that be our search bar.

**Comment by olivierboucher** [comment]
Yeah, if that is easier. Also, we could have a side menu on the left. Containing search, options, account, settings etc. The only problem I see with this is that it's not clear for the user. Even the long press used for the chat/video quality. This idea of gesture came from the Netflix app, but if you don't tell the user he may never know.

**Comment by waterskier2007** [comment]
Also, fyi the search api does not return viewer count, so we can't display that

**Comment by waterskier2007** [comment]
I've got it working well with a normal text field.

**Comment by olivierboucher** [comment]
By querying /search/streams you can get the viewers count ! Sorry for misleading

**Comment by olivierboucher** [comment]
"streams": [
    {
      "game": "StarCraft II: Heart of the Swarm",
      "viewers": 2123,....

From doc

**Comment by waterskier2007** [comment]
Yeah for sure, I was talking about the games search. In the games/top request you get viewers, but not in the search

**Comment by olivierboucher** [comment]
For /search/games we can use the "popularity" maybe?

**Comment by waterskier2007** [comment]
Possible. I'm not sure what that's measuring exactly. Like what's the possible range of values.

**Comment by waterskier2007** [comment]
This one is pretty much implemented after #31, other than I don't know what to display for the subtitle on searched games (we could just have it be blank)
