### ISSUE TITLE
TwitchApi models

### ISSUE THREAD

**Issue by olivierboucher** [StreamCenter/StreamCenter#27]
It's not clear from TwitchAPI whether a JSON property is optional or not. If you look at TwitchChannel.swift you'll see that some properties have the optional mark : 
- broadcasterLanguage
- logo
- videoBanner

I found those with random crashes happening at first. We should make sure that every optional property is typed as optional even though everything seems to be OK now.

**Comment by waterskier2007** [comment]
Use guard statements. I can take this one if you want.
