### ISSUE TITLE
We need an app icon

### ISSUE THREAD

**Issue by waterskier2007** [StreamCenter/StreamCenter#29]
It's kind of a big deal ;)

EDIT (Olivier): We also need to talk on the top self display !

**Comment by olivierboucher** [comment]
Will contact some graphic artists I know. This goes with the app name !

**Comment by mkral** [comment]
Just a reminder to use the parallax photoshop plugin

**Comment by mkral** [comment]
and we should design the icon in more than 1 layer IMO to utilize the cool new icons.

**Comment by olivierboucher** [comment]
Yes ofc !!

**Comment by waterskier2007** [comment]
Yes, a top shelf icon is important too. I'll take a look and see if I can find some examples in the documentation
