### ISSUE TITLE
Chat is sometimes crashing

### ISSUE THREAD

**Issue by olivierboucher** [StreamCenter/StreamCenter#3]
The implementation of the chat was really complex and sometimes it crashes. It involves GDC and is uncommented. If any of you guys encounter the bug **by the time I comment as much as possible out of it**, please let me know your insights :)

**Comment by olivierboucher** [comment]
Here is how it works for reference 
![Schema](https://github.com/OlivierBoucher/olivierboucher.github.io/blob/master/images/twitchDiag.png?raw=true)

**Comment by mkral** [comment]
I think I may have figured out the crashing. I added an exception breakpoint and it always seemed to crash when the message string contained "\U0000fffc" so I added 

```
var string = attrMsg.string

string = string.stringByReplacingOccurrencesOfString("\u{fffc}", withString: "");
```

and it's been running with chat for a long time but I want to leave it up and add some unit tests for the `getAttributedStringForMessage` function

**Comment by olivierboucher** [comment]
Nice ! I'm working on documentation / refactoring on a different branch right now. Mainly working on controller/views. Let's make sure we touch different things to avoid conflicts :+1:

**Comment by olivierboucher** [comment]
Closing this because of #57 & #58
