### ISSUE TITLE
twitch login

### ISSUE THREAD

**Issue by waterskier2007** [StreamCenter/StreamCenter#30]
Do we know if this will even be possible? Without having a browser on the appleTV, will we be able to login using the twitch api?

**Comment by chayelheinsen** [comment]
Take a look at this. http://stephenradford.me/oauth-login-on-tvos/ I think this is the only possible way to do it.

**Comment by olivierboucher** [comment]
Depends on the POST request generated by the web form. We may be able to simulate it

**Comment by olivierboucher** [comment]
@waterskier2007 Should I close this?

**Comment by waterskier2007** [comment]
Yep
Brendan Kirchner
brendankirchner@me.com
