### ISSUE TITLE
Top Shelf Image

### ISSUE THREAD

**Issue by waterskier2007** [StreamCenter/StreamCenter#43]
we need one

**Comment by olivierboucher** [comment]
Can't this be dynamic? If so, we have alot more options

**Comment by waterskier2007** [comment]
Static image only

**Comment by waterskier2007** [comment]
Image should be 1920px by 720px

**Comment by olivierboucher** [comment]
![streamcentertvwandbluebg](https://cloud.githubusercontent.com/assets/6015183/10492458/37d312dc-727a-11e5-9482-6342f2daaa1c.png)

Temporary solution

**Comment by waterskier2007** [comment]
I've added this to the develop branch. Will merge later

**Comment by waterskier2007** [comment]
Needs to be 1920x720, that's 1920x768

**Comment by olivierboucher** [comment]
OK will fix

**Comment by waterskier2007** [comment]
It's not urgent, it's just an annoying warning in Xcode

**Comment by waterskier2007** [comment]
![streamcentertvwandbluebg](https://cloud.githubusercontent.com/assets/2089840/10542726/4cf59b98-73e8-11e5-865c-9fec21f221a6.png)

**Comment by waterskier2007** [comment]
that's in the correct resolution

**Comment by olivierboucher** [comment]
Incorporated in 1631f465d2d48aedc8f6452192a9d6d911090389
