### ISSUE TITLE
Create a custom library for RTMP

### ISSUE THREAD

**Issue by olivierboucher** [StreamCenter/StreamCenter#59]
Can we do this? There's no free library atm.

**Comment by waterskier2007** [comment]
It may not really be necessary. RTMP seems to be an old technology that is being replaced by HTTP live streaming. Not sure we want to spend a ton of time trying to make our own library. All of the RTMP libraries I have found for iOS are really outdated.

**Comment by olivierboucher** [comment]
Noted. Let's see if we encounter any of this format with other integrations
