### ISSUE TITLE
Remove Back button from channels list view

### ISSUE THREAD

**Issue by mkral** [StreamCenter/StreamCenter#7]
There is no need for a back button, and it causes the back button to be in focus immediately. A user would just use the home button to return the "popular" streams page.

**Comment by mkral** [comment]
@OlivierBoucher Do you agree?

**Comment by mkral** [comment]
From Apple's HIG for Apple TV:

> "Implement backward navigation by way of the Menu button. To create an easy and predictable navigation experience, let users navigate backward with the remote’s Menu button. During gameplay, pressing Menu should return to the game main menu or toggle an in-game menu that provides an option to return to the game main menu. Pressing Menu at the top level of an app or game should always exit to the Apple TV Home screen.
> 
> **Avoid displaying a back button.** People know that pressing Menu takes them back, so don’t waste space in your app with an extra control that duplicates this behavior. If the only visible button purchases or deletes something, however, it is good practice to include a Cancel button that returns to the previous screen."

**Comment by olivierboucher** [comment]
Perfect, thanks for the find @mkral. Lets remove this
