### ISSUE TITLE
How and Where do I run pod install inside the project directory to install dependencies?

### ISSUE THREAD

**Issue by Shawzborne** [StreamCenter/StreamCenter#79]
How and Where do I run pod install inside the project directory to install dependencies?

sorry I'm a newb

**Comment by waterskier2007** [comment]
if you open a terminal window and cd to the root of the project you should just be able to run pod install

follow the installation instructions here to get cocoa pods up and running on your machine https://guides.cocoapods.org/using/getting-started.html
